### ISSUE TITLE
depends on cornernote/minetest-craft_guide by name

### ISSUE THREAD

**Issue by stormchaser3000** [cornernote/minetest-skyblock#12]
as the title states

**Comment by cornernote** [comment]
yes, its one of the feats (level3, place a Craft Guide)

this allows for players to be able to see all the things they can make in the skyblock world

what do you suggest?

**Comment by stormchaser3000** [comment]
adding the cornernote/minetest-craft_guide code to a mod here that is only used if cornernode/minetest-craft_guide is not installed

**Comment by cornernote** [comment]
would you be able to do a pull request with this code ?

**Comment by stormchaser3000** [comment]
i could try.

**Comment by cornernote** [comment]
ideally (and eventually) we will use the mini craft guide as a built-in replacement

the only thing missing is a page with the list of all recipies

**Comment by stormchaser3000** [comment]
well time to bust out atom

**Comment by cornernote** [comment]
do you think you can make a formspec page  with buttons for all the craftable items ?

do you want to chat in realtime?  try gitter:

https://gitter.im/cornernote/minetest-skyblock

**Comment by cornernote** [comment]
now it uses unified_inventory, closing this issue
