### ISSUE TITLE
Server crashing when specific player joins

### ISSUE THREAD

**Issue by thatgraemeguy** [cornernote/minetest-skyblock#25]
2015-08-05 12:36:40: ACTION[ServerThread]: deadlycreature [1.2.3.4] joins game. 
    2015-08-05 12:36:40: ACTION[ServerThread]: deadlycreature joins game. List of players: thatgraemeguy deadlycreature
    12:36:45: WARNING: Undeclared global variable "level" accessed at .../../mods/skyblock/skyblock_levels/skyblock.feats.lua:175
    2015-08-05 12:36:45: ERROR[main]: UNRECOVERABLE error occurred. Stopping server. Please fix the following error:
    2015-08-05 12:36:45: ERROR[main]: Lua: .../../mods/skyblock/skyblock_levels/skyblock.feats.lua:175: attempt to index field '?' (a nil value)
    2015-08-05 12:36:45: ERROR[main]: stack traceback:
    2015-08-05 12:36:45: ERROR[main]:       .../../mods/skyblock/skyblock_levels/skyblock.feats.lua:175: in function <.../../mods/skyblock/skyblock_levels/skyblock.feats.lua:171>

    In thread 7fceb96f8780:
    /home/graeme/skyblock/src/server.cpp:511: void Server::step(float): A fatal error occurred: Lua: .../../mods/skyblock/skyblock_levels/skyblock.feats.lua:175: attempt to index field '?' (a nil value)
    stack traceback:
            .../../mods/skyblock/skyblock_levels/skyblock.feats.lua:175: in function <.../../mods/skyblock/skyblock_levels/skyblock.feats.lua:171>
    Debug stacks:
    DEBUG STACK FOR THREAD 7fceb1344700:
    #0  virtual void* EmergeThread::Thread()
    (Leftover data: #1  MapBlock* ServerMap::loadBlock(v3s16))
    (Leftover data: #2  void ServerMap::loadBlock(std::string*, v3s16, MapSector*, bool))
    (Leftover data: #3  void ItemStack::deSerialize(std::istream&, IItemDefManager*))
    DEBUG STACK FOR THREAD 7fceb1b45700:
    #0  virtual void* CurlFetchThread::Thread()
    DEBUG STACK FOR THREAD 7fceb2346700:
    #0  virtual void* ServerThread::Thread()
    #1  void Server::Receive()
    (Leftover data: #2  void Server::SendBlocks(float))
    (Leftover data: #3  void RemoteClient::GetNextBlocks(ServerEnvironment*, EmergeManager*, float, std::vector<PrioritySortedBlockTransfer>&))
    (Leftover data: #4  void ItemStack::serialize(std::ostream&) const)
    (Leftover data: #5  bool getCraftingResult(Inventory*, ItemStack&, std::vector<ItemStack>&, bool, IGameDef*))
    (Leftover data: #6  void ItemStack::deSerialize(std::istream&, IItemDefManager*))
    DEBUG STACK FOR THREAD 7fceb96f8780:
    #0  int main(int, char**)
    #1  Dedicated server branch
    #2  void dedicated_server_loop(Server&, bool&)
    #3  void Server::step(float)

**Comment by cornernote** [comment]
yep, thats definately a bug.  pushed a fix, let me know if you still have issues

**Comment by thatgraemeguy** [comment]
Great, thanks. We noticed afterward it wasn't when he joined, but when either of us placed a door. I just placed a door without a crash, looks good!
