### ISSUE TITLE
Another crash "Lua: Invalid position (expected table got nil)."

### ISSUE THREAD

**Issue by thatgraemeguy** [cornernote/minetest-skyblock#27]
2015-08-05 13:30:20: ACTION[ServerThread]: thatgraemeguy uses bucket:bucket_empty, pointing at [node under=1600,5,1600 above=1600,6,1600]
    13:30:20: WARNING: Assignment to undeclared global "liquiddef" inside a function at .../../mods/skyblock/skyblock_levels/skyblock.feats.lua:231.
    2015-08-05 13:30:20: ACTION[ServerThread]: thatgraemeguy completed the quest "collect_water" on level 2
    2015-08-05 13:30:20: ACTION[ServerThread]: thatgraemeguy completed level 2
    13:30:23: WARNING: Undeclared global variable "feats" accessed at .../mods/skyblock/skyblock_levels/skyblock.levels.3.lua:199
    2015-08-05 13:30:23: ERROR[main]: UNRECOVERABLE error occurred. Stopping server. Please fix the following error:
    2015-08-05 13:30:23: ERROR[main]: Lua: Invalid position (expected table got nil).

    In thread 7f4400ea8780:
    /home/graeme/skyblock/src/server.cpp:511: void Server::step(float): A fatal error occurred: Lua: Invalid position (expected table got nil).
    Debug stacks:
    DEBUG STACK FOR THREAD 7f43f8af4700:
    #0  virtual void* EmergeThread::Thread()
    (Leftover data: #1  MapBlock* ServerMap::loadBlock(v3s16))
    (Leftover data: #2  void ServerMap::loadBlock(std::string*, v3s16, MapSector*, bool))
    (Leftover data: #3  void ItemStack::deSerialize(std::istream&, IItemDefManager*))
    DEBUG STACK FOR THREAD 7f43f92f5700:
    #0  virtual void* CurlFetchThread::Thread()
    DEBUG STACK FOR THREAD 7f43f9af6700:
    #0  virtual void* ServerThread::Thread()
    #1  void Server::Receive()
    (Leftover data: #2  void Server::SendBlocks(float))
    (Leftover data: #3  void RemoteClient::GetNextBlocks(ServerEnvironment*, EmergeManager*, float, std::vector<PrioritySortedBlockTransfer>&))
    (Leftover data: #4  void ItemStack::serialize(std::ostream&) const)
    (Leftover data: #5  bool getCraftingResult(Inventory*, ItemStack&, std::vector<ItemStack>&, bool, IGameDef*))
    (Leftover data: #6  void ItemStack::deSerialize(std::istream&, IItemDefManager*))
    DEBUG STACK FOR THREAD 7f4400ea8780:
    #0  int main(int, char**)
    #1  Dedicated server branch
    #2  void dedicated_server_loop(Server&, bool&)
    #3  void Server::step(float)
    (Leftover data: #4  void Server::SendAccessDenied_Legacy(irr::u16, const wstring&))

**Comment by thatgraemeguy** [comment]
Still crashes. Seems to happen when I place a water source.

    13:38:28: WARNING: Undeclared global variable "feats" accessed at .../mods/skyblock/skyblock_levels/skyblock.levels.3.lua:199
    2015-08-05 13:38:28: ERROR[main]: UNRECOVERABLE error occurred. Stopping server. Please fix the following error:
    2015-08-05 13:38:28: ERROR[main]: Lua: Invalid position (expected table got nil).

    In thread 7f32659ea780:
    /home/graeme/skyblock/src/server.cpp:511: void Server::step(float): A fatal error occurred: Lua: Invalid position (expected table got nil).
    Debug stacks:
    DEBUG STACK FOR THREAD 7f325d636700:
    #0  virtual void* EmergeThread::Thread()
    #1  MapBlock* ServerMap::loadBlock(v3s16)
    #2  void ServerMap::loadBlock(std::string*, v3s16, MapSector*, bool)
    (Leftover data: #3  void ItemStack::deSerialize(std::istream&, IItemDefManager*))
    DEBUG STACK FOR THREAD 7f325de37700:
    #0  virtual void* CurlFetchThread::Thread()
    DEBUG STACK FOR THREAD 7f325e638700:
    #0  virtual void* ServerThread::Thread()
    #1  void Server::Receive()
    (Leftover data: #2  void Server::SendBlocks(float))
    (Leftover data: #3  void Server::SendBlockNoLock(irr::u16, MapBlock*, irr::u8, irr::u16))
    (Leftover data: #4  void ItemStack::serialize(std::ostream&) const)
    (Leftover data: #5  bool getCraftingResult(Inventory*, ItemStack&, std::vector<ItemStack>&, bool, IGameDef*))
    DEBUG STACK FOR THREAD 7f32659ea780:
    #0  int main(int, char**)
    #1  Dedicated server branch
    #2  void dedicated_server_loop(Server&, bool&)
    #3  void Server::step(float)

**Comment by thatgraemeguy** [comment]
Fixed now, thanks.

**Comment by cornernote** [comment]
another bug that i put in today... should be getting to the end of them now (hopefully)
