### ISSUE TITLE
Not sure if this one is a skyblock error: "ERROR[main]: Lua: error in error handling"

### ISSUE THREAD

**Issue by thatgraemeguy** [cornernote/minetest-skyblock#28]
2015-08-05 18:44:50: ERROR[main]: UNRECOVERABLE error occurred. Stopping server. Please fix the following error:
    2015-08-05 18:44:50: ERROR[main]: Lua: error in error handling

    In thread 7f2241deb780:
    /home/graeme/skyblock/src/server.cpp:511: void Server::step(float): A fatal error occurred: Lua: error in error handling
    Debug stacks:
    DEBUG STACK FOR THREAD 7f2239a37700:
    #0  virtual void* EmergeThread::Thread()
    (Leftover data: #1  MapBlock* ServerMap::loadBlock(v3s16))
    (Leftover data: #2  void ServerMap::loadBlock(std::string*, v3s16, MapSector*, bool))
    (Leftover data: #3  void ItemStack::deSerialize(std::istream&, IItemDefManager*))
    DEBUG STACK FOR THREAD 7f223a238700:
    #0  virtual void* CurlFetchThread::Thread()
    DEBUG STACK FOR THREAD 7f223aa39700:
    #0  virtual void* ServerThread::Thread()
    #1  void Server::Receive()
    (Leftover data: #2  void Server::SendBlocks(float))
    (Leftover data: #3  void Server::SendBlockNoLock(irr::u16, MapBlock*, irr::u8, irr::u16))
    (Leftover data: #4  void ItemStack::serialize(std::ostream&) const)
    (Leftover data: #5  bool getCraftingResult(Inventory*, ItemStack&, std::vector<ItemStack>&, bool, IGameDef*))
    (Leftover data: #6  void ItemStack::deSerialize(std::istream&, IItemDefManager*))
    DEBUG STACK FOR THREAD 7f2241deb780:
    #0  int main(int, char**)
    #1  Dedicated server branch
    #2  void dedicated_server_loop(Server&, bool&)
    #3  void Server::step(float)
    (Leftover data: #4  void Server::SendAccessDenied_Legacy(irr::u16, const wstring&))

**Comment by cornernote** [comment]
> @kwolekr commented 2 minutes ago
> Try updating to the latest version.

https://github.com/minetest/minetest/issues/3011#issuecomment-128228867

**Comment by cornernote** [comment]
closing this issue as it seems to be a problem in minetest (or at least we cant find the issue until minetest handles the error correctly)

**Comment by cornernote** [comment]
OldCoder believes this is because of lines commented from skyblock.feats.lua

Try uncomment those.

**Comment by thatgraemeguy** [comment]
I haven't had this issue in 10+ days now.
