### ISSUE TITLE
achievments and skyblock mods don't work atm

### ISSUE THREAD

**Issue by stormchaser3000** [cornernote/minetest-skyblock#4]
17:27:37: ERROR[main]: ========== ERROR FROM LUA ===========
17:27:37: ERROR[main]: Failed to load and run script from
17:27:37: ERROR[main]: /home/stormchaser3000/minetest-0.4.12/bin/../mods/minetest-skyblock/achievements/init.lua:
17:27:37: ERROR[main]: .../bin/../mods/minetest-skyblock/skyblock/api_skyblock.lua:320: bad argument #1 to 'pairs' (table expected, got nil)
17:27:37: ERROR[main]: stack traceback:
17:27:37: ERROR[main]:  [C]: in function 'pairs'
17:27:37: ERROR[main]:  .../bin/../mods/minetest-skyblock/skyblock/api_skyblock.lua:320: in function 'registered'
17:27:37: ERROR[main]:  ...4.12/bin/../mods/minetest-skyblock/achievements/init.lua:201: in main chunk
17:27:37: ERROR[main]: ======= END OF ERROR FROM LUA ========

**Comment by cornernote** [comment]
I think its because buckets isnt loaded.  I added it to the depends.txt, can you try again now?

**Comment by stormchaser3000** [comment]
yep it works now.

**Comment by cornernote** [comment]
there was probably a boat load of bugs as i refacored a lot of code last night.  i just did a push which should be more stable
