### ISSUE TITLE
Block above the "?" block is destroyed when you complete a quest with water reward

### ISSUE THREAD

**Issue by sfan5** [cornernote/minetest-skyblock#43]
```
<cornernote> how to avoid it ?
<sfan5> search for a free space and only destroy the node above as last resort
```

**Comment by thatgraemeguy** [comment]
Alternately, make the reward appear in the "rewards" slots like all other rewards, as a bucket of water, rather than placing a water source in the world.

**Comment by sfan5** [comment]
One of the quests is to pick up the water so you can't just give the player a water bucket.

**Comment by thatgraemeguy** [comment]
Well, you can if you change the code to do that. :)

**Comment by cornernote** [comment]
I was thinking to remove the block that I would otherwise delete, and put the block into the rewards slot.

**Comment by thatgraemeguy** [comment]
This also stops your world becoming littered with a huge amount of falling water that is going to just sit there until the end of time because there's no reasonably good way to clean it up.

**Comment by cornernote** [comment]
falling water should be fine now the cloud bedrock is there

**Comment by thatgraemeguy** [comment]
@cornernote that might work too. I previously placed a protection block above the quest block and the water ate it.

**Comment by thatgraemeguy** [comment]
Right, that is true, I'd forgotten about the cloud. Still messy on my server as most of the central islands generated before that, and at some point I lowered the world bottom a bit, so I have parts with no bottom, parts with cloud above the current world bottom, and parts with the cloud bottom slightly below world bottom. Some players have built structures on the in-between cloud already.
