### ISSUE TITLE
Inactive Reward field

### ISSUE THREAD

**Issue by Alvarion** [cornernote/minetest-skyblock#54]
In latest build of all components have not active rewards fields and not reward given after quest end.

Its problem from skyblock mod or unified inventory mod?

![skyblock_levels_rewards](https://cloud.githubusercontent.com/assets/14175702/9729327/f81dff30-560e-11e5-8fb8-fe7d91ea94f5.png)

Thx

**Comment by Alvarion** [comment]
So i Test it without unified inventory and issue is same .. Rewards not active :(

**Comment by cornernote** [comment]
I just created a new world with the latest version, and can't replicate this issue.

Do you have any other mods?  Can you try disable everything except the mods in the skyblock modpack?

**Comment by Alvarion** [comment]
I have only Skyblock, Unified inventory and protector mods ..

**Comment by Alvarion** [comment]
OK may Fault .. i try to create new world and everything works fine .. sry
