### ISSUE TITLE
Missing local declaration? : WARNING: Undeclared global variable "dyelocal" 

### ISSUE THREAD

**Issue by Alvarion** [cornernote/minetest-skyblock#62]
Error: WARNING: Undeclared global variable "dyelocal"  accessed at ...st-skyblock/skyblock_levels/skyblock.craft_guide.lua:22

**Comment by LeMagnesium** [comment]
I already noticed that error too. I did not bother fixing it since it was a minor error but it's still a good thing to clear logs from such warnings.
It's fixed on @Ombridride's server. You can use the code from there or merge my branch 'fix_global_variable'.

**Comment by cornernote** [comment]
It's because dye mod declares it as local. You have to make it global, and
I should do a PR to minetest_game to change it.

**Comment by cornernote** [comment]
line that needs to be changed:
https://github.com/minetest/minetest_game/blob/master/mods/dye/init.lua#L9

pull request to make those things global:
https://github.com/minetest/minetest_game/pull/689

**Comment by LeMagnesium** [comment]
I did not see that. Thanks for the PR.

**Comment by LeMagnesium** [comment]
According to what PilzAdam declared [here](https://github.com/minetest/minetest_game/pull/689#issuecomment-144492946) I rewrote the piece of code looking for those placeholders, and added one that I noticed a while ago was missing.
