### ISSUE TITLE
ladder quest uncompletable

### ISSUE THREAD

**Issue by DanHolli123** [cornernote/minetest-skyblock#71]
on the newest two versions of this mod it is impossible to complete the ladder quest
it won't count placed ladders, wood OR iron
this is in singleplayer

**Comment by LeMagnesium** [comment]
The ladder's item name changed, it's not `default:ladder` any more.
I've made a PR to update the code, you can copy those changes into your files : #72.

**Comment by cornernote** [comment]
Thanks for reporting and for the PR!
