### ISSUE TITLE
Please tag releases

### ISSUE THREAD

**Issue by SnarkBoojum** [cornernote/minetest-skyblock#78]
Hi,

could you tag a new release? The most recent one was on the 9th august 2015...

Thanks!

**Comment by cornernote** [comment]
That's about when I worked on it last!  Haha

I see there are many commits since then, mostly from contributing developers/players.

I have drafted a new release.

**Comment by SnarkBoojum** [comment]
Thanks!

(While packaging it, I noticed that the ogg files in skyblock_levels/sounds/  are executable.)
