### ISSUE TITLE
Move to Minetest Mods

### ISSUE THREAD

**Issue by Panquesito7** [cornernote/minetest-skyblock#84]
It would be great to see this mod in [Minetest Mods](https://minetest-mods.github.io).
IMHO, it will be more maintained.

It'll have more popularity, and users will be able to find it easier.
Thanks for your attention! 🙂

**Comment by cornernote** [comment]
what's needed to move it ?

**Comment by Panquesito7** [comment]
See https://minetest-mods.github.io/ for information.

**Comment by cornernote** [comment]
I have initiated the request - https://github.com/minetest-mods/minetest-mods.github.io/issues/108

**Comment by Panquesito7** [comment]
If you're inactive in maintaining this project, I'd like to help to maintain it. Of course, request a review from you or somebody experienced with Skyblock's code. Thank you. 🙂
