### ISSUE TITLE
Please tag new releases

### ISSUE THREAD

**Issue by SnarkBoojum** [cornernote/minetest-skyblock#88]
There has been no new version tagged since 0.2.4 more then three years ago.

**Comment by SnarkBoojum** [comment]
Tagging is a simple "git tag 0.3.14" away, so I'm not asking for the moon here ;-)

And even if you upload to ContentDB, that will also help you know what commit you uploaded precisely...

**Comment by cornernote** [comment]
Sorry everyone, i've had some other stuff to deal with... I made a new 0.3.0 release, and this repo will be moving to a new loving home soon.

**Comment by Panquesito7** [comment]
> Sorry everyone, i've had some other stuff to deal with... I made a new 0.3.0 release, and this repo will be moving to a new loving home soon.

No worries! Glad to have you back! 😃
